export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const DRAW_CARD = 'DRAW_CARD';
export const DISCARD_CARD = 'DISCARD_CARD';
export const SHUFFLE_DISCARD_INTO_DECK = 'SHUFFLE_DISCARD_INTO_DECK';
export const PLAY_CARD = 'PLAY_CARD';
export const MOVE_CARD = 'MOVE_CARD';